# Generated by Django 5.0.1 on 2024-02-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-01-09'),
            preserve_default=False,
        ),
    ]
